---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-8cd37e7d1de9a808fe20309c0c9f3c0d
  name: wego-test-app-foi17aat
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/my-test-org-23/wego-test-app-foi17aat.git
