apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-8ctufq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-8ctufq
  namespace: my-nginx-8ctufq
  labels:
    name: nginx-8ctufq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-8ctufq
  template:
    metadata:
      namespace: my-nginx-8ctufq
      labels:
        name: nginx-8ctufq
    spec:
      containers:
      - name: nginx-8ctufq
        image: nginx
        ports:
        - containerPort: 80

